pipeline {
    agent any

    environment {
        APP_DIR     = "/home/ubuntu/django-app"
        VENV_DIR    = "venv"
        DJANGO_PORT = "8000"
        DJANGO_EC2  = "ubuntu@13.215.201.183"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Vidh17/Jenkins-demo.git'
            }
        }

        stage('Install Dependencies (Jenkins)') {
            steps {
                dir('Docker') {
                    sh '''
                    python3 -m venv ${VENV_DIR}
                    . ${VENV_DIR}/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Django Checks') {
            steps {
                dir('Docker') {
                    sh '''
                    . ${VENV_DIR}/bin/activate
                    python manage.py check
                    '''
                }
            }
        }

        stage('Run Migrations (Jenkins Test)') {
            steps {
                dir('Docker') {
                    sh '''
                    . ${VENV_DIR}/bin/activate
                    python manage.py migrate --noinput
                    '''
                }
            }
        }

        stage('Deploy to Django EC2') {
            steps {
                sh '''
                ssh -o StrictHostKeyChecking=no ${DJANGO_EC2} "mkdir -p ${APP_DIR}"

                scp -o StrictHostKeyChecking=no -r \
                Docker/app1 Docker/app4 Docker/myweb \
                Docker/manage.py Docker/requirements.txt Docker/django.sh \
                ${DJANGO_EC2}:${APP_DIR}

                ssh -o StrictHostKeyChecking=no ${DJANGO_EC2} "
                    cd ${APP_DIR} &&
                    rm -rf ${VENV_DIR} &&
                    python3 -m venv ${VENV_DIR} &&
                    . ${VENV_DIR}/bin/activate &&
                    pip install --upgrade pip &&
                    pip install -r requirements.txt &&
                    chmod +x django.sh &&
                    ./django.sh
                "
                '''
            }
        }
    }
}
